### ISSUE TITLE
请问这是什么问题？

### ISSUE THREAD

**Issue by yaogengcheng** [wlguan/tf2-yolo3#2]
Traceback (most recent call last):
  File "main_voc.py", line 34, in <module>
    optimizer=optimizer,
  File "/home/ygc/下载/tensorflow2.0-yolov3-master/trainers/trainer_voc.py", line 6, in __init__
    super().__init__(args, model, optimizer)
  File "/home/ygc/下载/tensorflow2.0-yolov3-master/trainers/base_trainer.py", line 35, in __init__
    self.anchors = eval('{}_ANCHOR_{}'.format(self.args.dataset_name.upper(),self.net_size))
  File "<string>", line 1, in <module>
NameError: name 'VOC_ANCHOR_608' is not defined

**Comment by apxlwl** [comment]
@yaogengcheng 你好，如果要以608为输入分辨率，需要先在config.py文件中给出VOC_ANCHOR_608的大小。可以将VOC_ANCHOR_480中对应的anchor大小乘以相应比例即608/408。
